trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Docker@2
  displayName: 'Build and push docker-image'
  inputs:
    containerRegistry: 'dockerhub'
    repository: 'dhedegaard/discord-lag-fixer'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- task: SSH@0
  displayName: 'Deploy new container'
  enabled: 'false' 
  inputs:
    sshEndpoint: 'dennis@ymir'
    runOptions: 'commands'
    commands: 'bash -e -x -c "
        cd discord-lag-fixer && 
        git pull --ff-only && 
        docker-compose pull && 
        docker-compose up --build -d
      "'
