trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Docker@2
  displayName: 'Build and push docker-image'
  inputs:
    containerRegistry: 'dockerhub'
    repository: 'dhedegaard/discord-lag-fixer'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- task: SSH@0
  displayName: 'Deploy new container'
  inputs:
    sshEndpoint: 'dennis@ymir'
    runOptions: 'commands'
    commands: 'bash -e -x -c "
        docker pull dhedegaard/discord-lag-fixer &&
        docker stack deploy -c discord-lag-fixer/docker-compose.yml discord-lag-fixer
      "'
